resources:
    med:
        mem: "16000MB"
        mem_mb: 16000
        cpu: 8
        time: "04:00:00"
trimnami:
    args:
        reads: "test/"
        host: "test/ref.fna"
        outfmt:
            "fastq.gz"
#            "fastq"
#            "fasta.gz"
#            "fasta"
        steps:
          - host_rm
          - fastp
#          - prinseq
#          - roundAB
#          - notrim
#          - cutadapt
#          - filtlong
#          - subsample
        minimap: "sr"
        fastqc: true
        output: "trimnami.out/"
        output_paths:
            results: "results/"
            reports: "reports/"
            temp: "temp/"
            log: "logs/"
            bench: "benchmarks/"
            trimnami_log: "trimnami.log"
    container:
        bbmap:
            "oras://quay.io/beardymcjohnface/trimnami_bbmap:0.0.0"
        cutadapt:
            "oras://quay.io/beardymcjohnface/trimnami_cutadapt:0.0.0"
        fastp:
            "oras://quay.io/beardymcjohnface/trimnami_fastp:0.0.0"
        fastqc:
            "oras://quay.io/beardymcjohnface/trimnami_fastqc:0.0.0"
        filtlong:
            "oras://quay.io/beardymcjohnface/trimnami_filtlong:0.0.0"
        minimap2:
            "oras://quay.io/beardymcjohnface/trimnami_minimap2:0.0.0"
        multiqc:
            "oras://quay.io/beardymcjohnface/trimnami_multiqc:0.0.0"
        prinseq:
            "oras://quay.io/beardymcjohnface/trimnami_prinseq:0.0.0"
        rasusa:
            "oras://quay.io/beardymcjohnface/trimnami_rasusa:0.0.0"
        seqtk:
            "oras://quay.io/beardymcjohnface/trimnami_seqtk:0.0.0"
    qc:
        compression:
            1
        minimapIndex:
            -I 8G
        hostRemoveFlagstat:
            -f 4
            -F 3584
        cutadapt:
            params:
                -m 40
            adapters:
                "IlluminaAdapters.fa"
#                "nebnext_adapters.fa"
        subsample:
            --num 1g
#        subsample:
#            --bases 1g
#        subsample:
#            --frac 0.5
#        subsample:
#            --coverage 100
#            --genome-size 1m
        fastp:
            --qualified_quality_phred 15
            --length_required 90
            --cut_tail 
            --cut_tail_window_size 25
            --cut_tail_mean_quality 15
            --dedup
            --dup_calc_accuracy 4
            --trim_poly_x
            --detect_adapter_for_pe
        prinseq:
            -min_len 60 
            -min_qual_mean 25 
            -ns_max_n 1 
            -derep 1
            -out_format 0 
            -trim_tail_left 5 
            -trim_tail_right 5
            -ns_max_n 5  
            -trim_qual_type min 
            -trim_qual_left 30
            -trim_qual_right 30 
            -trim_qual_window 10
        filtlong:
            --min_length 1000
            --keep_percent 95